// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/boat_protos.proto

package com.github.uuigaz.messages;

public final class BoatProtos {
  private BoatProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CoordinateOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 x = 1;
    boolean hasX();
    int getX();
    
    // required uint32 y = 2;
    boolean hasY();
    int getY();
  }
  public static final class Coordinate extends
      com.google.protobuf.GeneratedMessage
      implements CoordinateOrBuilder {
    // Use Coordinate.newBuilder() to construct.
    private Coordinate(Builder builder) {
      super(builder);
    }
    private Coordinate(boolean noInit) {}
    
    private static final Coordinate defaultInstance;
    public static Coordinate getDefaultInstance() {
      return defaultInstance;
    }
    
    public Coordinate getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.uuigaz.messages.BoatProtos.internal_static_messages_Coordinate_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.uuigaz.messages.BoatProtos.internal_static_messages_Coordinate_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint32 x = 1;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getX() {
      return x_;
    }
    
    // required uint32 y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getY() {
      return y_;
    }
    
    private void initFields() {
      x_ = 0;
      y_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, y_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.github.uuigaz.messages.BoatProtos.Coordinate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Coordinate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Coordinate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Coordinate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Coordinate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Coordinate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Coordinate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.Coordinate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.Coordinate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Coordinate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.uuigaz.messages.BoatProtos.Coordinate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.github.uuigaz.messages.BoatProtos.CoordinateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.uuigaz.messages.BoatProtos.internal_static_messages_Coordinate_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.uuigaz.messages.BoatProtos.internal_static_messages_Coordinate_fieldAccessorTable;
      }
      
      // Construct using com.github.uuigaz.messages.BoatProtos.Coordinate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.uuigaz.messages.BoatProtos.Coordinate.getDescriptor();
      }
      
      public com.github.uuigaz.messages.BoatProtos.Coordinate getDefaultInstanceForType() {
        return com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance();
      }
      
      public com.github.uuigaz.messages.BoatProtos.Coordinate build() {
        com.github.uuigaz.messages.BoatProtos.Coordinate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.github.uuigaz.messages.BoatProtos.Coordinate buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.github.uuigaz.messages.BoatProtos.Coordinate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.github.uuigaz.messages.BoatProtos.Coordinate buildPartial() {
        com.github.uuigaz.messages.BoatProtos.Coordinate result = new com.github.uuigaz.messages.BoatProtos.Coordinate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.uuigaz.messages.BoatProtos.Coordinate) {
          return mergeFrom((com.github.uuigaz.messages.BoatProtos.Coordinate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.github.uuigaz.messages.BoatProtos.Coordinate other) {
        if (other == com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              x_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              y_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 x = 1;
      private int x_ ;
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getX() {
        return x_;
      }
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 y = 2;
      private int y_ ;
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getY() {
        return y_;
      }
      public Builder setY(int value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:messages.Coordinate)
    }
    
    static {
      defaultInstance = new Coordinate(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messages.Coordinate)
  }
  
  public interface BoatOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .messages.Coordinate co = 1;
    boolean hasCo();
    com.github.uuigaz.messages.BoatProtos.Coordinate getCo();
    com.github.uuigaz.messages.BoatProtos.CoordinateOrBuilder getCoOrBuilder();
  }
  public static final class Boat extends
      com.google.protobuf.GeneratedMessage
      implements BoatOrBuilder {
    // Use Boat.newBuilder() to construct.
    private Boat(Builder builder) {
      super(builder);
    }
    private Boat(boolean noInit) {}
    
    private static final Boat defaultInstance;
    public static Boat getDefaultInstance() {
      return defaultInstance;
    }
    
    public Boat getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.uuigaz.messages.BoatProtos.internal_static_messages_Boat_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.uuigaz.messages.BoatProtos.internal_static_messages_Boat_fieldAccessorTable;
    }
    
    public enum BoatType
        implements com.google.protobuf.ProtocolMessageEnum {
      CARRIER(0, 5),
      BATTLESHIP(1, 4),
      CRUISER(2, 3),
      DESTROYER(3, 2),
      SUBMARINE(4, 1),
      ;
      
      public static final int CARRIER_VALUE = 5;
      public static final int BATTLESHIP_VALUE = 4;
      public static final int CRUISER_VALUE = 3;
      public static final int DESTROYER_VALUE = 2;
      public static final int SUBMARINE_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static BoatType valueOf(int value) {
        switch (value) {
          case 5: return CARRIER;
          case 4: return BATTLESHIP;
          case 3: return CRUISER;
          case 2: return DESTROYER;
          case 1: return SUBMARINE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<BoatType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<BoatType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<BoatType>() {
              public BoatType findValueByNumber(int number) {
                return BoatType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.github.uuigaz.messages.BoatProtos.Boat.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final BoatType[] VALUES = {
        CARRIER, BATTLESHIP, CRUISER, DESTROYER, SUBMARINE, 
      };
      
      public static BoatType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private BoatType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:messages.Boat.BoatType)
    }
    
    private int bitField0_;
    // required .messages.Coordinate co = 1;
    public static final int CO_FIELD_NUMBER = 1;
    private com.github.uuigaz.messages.BoatProtos.Coordinate co_;
    public boolean hasCo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.github.uuigaz.messages.BoatProtos.Coordinate getCo() {
      return co_;
    }
    public com.github.uuigaz.messages.BoatProtos.CoordinateOrBuilder getCoOrBuilder() {
      return co_;
    }
    
    private void initFields() {
      co_ = com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getCo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, co_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, co_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.github.uuigaz.messages.BoatProtos.Boat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Boat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Boat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Boat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Boat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Boat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Boat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.Boat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.Boat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Boat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.uuigaz.messages.BoatProtos.Boat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.github.uuigaz.messages.BoatProtos.BoatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.uuigaz.messages.BoatProtos.internal_static_messages_Boat_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.uuigaz.messages.BoatProtos.internal_static_messages_Boat_fieldAccessorTable;
      }
      
      // Construct using com.github.uuigaz.messages.BoatProtos.Boat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (coBuilder_ == null) {
          co_ = com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance();
        } else {
          coBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.uuigaz.messages.BoatProtos.Boat.getDescriptor();
      }
      
      public com.github.uuigaz.messages.BoatProtos.Boat getDefaultInstanceForType() {
        return com.github.uuigaz.messages.BoatProtos.Boat.getDefaultInstance();
      }
      
      public com.github.uuigaz.messages.BoatProtos.Boat build() {
        com.github.uuigaz.messages.BoatProtos.Boat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.github.uuigaz.messages.BoatProtos.Boat buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.github.uuigaz.messages.BoatProtos.Boat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.github.uuigaz.messages.BoatProtos.Boat buildPartial() {
        com.github.uuigaz.messages.BoatProtos.Boat result = new com.github.uuigaz.messages.BoatProtos.Boat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (coBuilder_ == null) {
          result.co_ = co_;
        } else {
          result.co_ = coBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.uuigaz.messages.BoatProtos.Boat) {
          return mergeFrom((com.github.uuigaz.messages.BoatProtos.Boat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.github.uuigaz.messages.BoatProtos.Boat other) {
        if (other == com.github.uuigaz.messages.BoatProtos.Boat.getDefaultInstance()) return this;
        if (other.hasCo()) {
          mergeCo(other.getCo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCo()) {
          
          return false;
        }
        if (!getCo().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.github.uuigaz.messages.BoatProtos.Coordinate.Builder subBuilder = com.github.uuigaz.messages.BoatProtos.Coordinate.newBuilder();
              if (hasCo()) {
                subBuilder.mergeFrom(getCo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .messages.Coordinate co = 1;
      private com.github.uuigaz.messages.BoatProtos.Coordinate co_ = com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.github.uuigaz.messages.BoatProtos.Coordinate, com.github.uuigaz.messages.BoatProtos.Coordinate.Builder, com.github.uuigaz.messages.BoatProtos.CoordinateOrBuilder> coBuilder_;
      public boolean hasCo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.github.uuigaz.messages.BoatProtos.Coordinate getCo() {
        if (coBuilder_ == null) {
          return co_;
        } else {
          return coBuilder_.getMessage();
        }
      }
      public Builder setCo(com.github.uuigaz.messages.BoatProtos.Coordinate value) {
        if (coBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          co_ = value;
          onChanged();
        } else {
          coBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setCo(
          com.github.uuigaz.messages.BoatProtos.Coordinate.Builder builderForValue) {
        if (coBuilder_ == null) {
          co_ = builderForValue.build();
          onChanged();
        } else {
          coBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeCo(com.github.uuigaz.messages.BoatProtos.Coordinate value) {
        if (coBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              co_ != com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance()) {
            co_ =
              com.github.uuigaz.messages.BoatProtos.Coordinate.newBuilder(co_).mergeFrom(value).buildPartial();
          } else {
            co_ = value;
          }
          onChanged();
        } else {
          coBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearCo() {
        if (coBuilder_ == null) {
          co_ = com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance();
          onChanged();
        } else {
          coBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.github.uuigaz.messages.BoatProtos.Coordinate.Builder getCoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getCoFieldBuilder().getBuilder();
      }
      public com.github.uuigaz.messages.BoatProtos.CoordinateOrBuilder getCoOrBuilder() {
        if (coBuilder_ != null) {
          return coBuilder_.getMessageOrBuilder();
        } else {
          return co_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.github.uuigaz.messages.BoatProtos.Coordinate, com.github.uuigaz.messages.BoatProtos.Coordinate.Builder, com.github.uuigaz.messages.BoatProtos.CoordinateOrBuilder> 
          getCoFieldBuilder() {
        if (coBuilder_ == null) {
          coBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.github.uuigaz.messages.BoatProtos.Coordinate, com.github.uuigaz.messages.BoatProtos.Coordinate.Builder, com.github.uuigaz.messages.BoatProtos.CoordinateOrBuilder>(
                  co_,
                  getParentForChildren(),
                  isClean());
          co_ = null;
        }
        return coBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:messages.Boat)
    }
    
    static {
      defaultInstance = new Boat(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messages.Boat)
  }
  
  public interface ShotOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .messages.Coordinate co = 1;
    boolean hasCo();
    com.github.uuigaz.messages.BoatProtos.Coordinate getCo();
    com.github.uuigaz.messages.BoatProtos.CoordinateOrBuilder getCoOrBuilder();
  }
  public static final class Shot extends
      com.google.protobuf.GeneratedMessage
      implements ShotOrBuilder {
    // Use Shot.newBuilder() to construct.
    private Shot(Builder builder) {
      super(builder);
    }
    private Shot(boolean noInit) {}
    
    private static final Shot defaultInstance;
    public static Shot getDefaultInstance() {
      return defaultInstance;
    }
    
    public Shot getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.uuigaz.messages.BoatProtos.internal_static_messages_Shot_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.uuigaz.messages.BoatProtos.internal_static_messages_Shot_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .messages.Coordinate co = 1;
    public static final int CO_FIELD_NUMBER = 1;
    private com.github.uuigaz.messages.BoatProtos.Coordinate co_;
    public boolean hasCo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.github.uuigaz.messages.BoatProtos.Coordinate getCo() {
      return co_;
    }
    public com.github.uuigaz.messages.BoatProtos.CoordinateOrBuilder getCoOrBuilder() {
      return co_;
    }
    
    private void initFields() {
      co_ = com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getCo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, co_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, co_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.github.uuigaz.messages.BoatProtos.Shot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Shot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Shot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Shot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Shot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Shot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Shot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.Shot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.Shot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Shot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.uuigaz.messages.BoatProtos.Shot prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.github.uuigaz.messages.BoatProtos.ShotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.uuigaz.messages.BoatProtos.internal_static_messages_Shot_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.uuigaz.messages.BoatProtos.internal_static_messages_Shot_fieldAccessorTable;
      }
      
      // Construct using com.github.uuigaz.messages.BoatProtos.Shot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (coBuilder_ == null) {
          co_ = com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance();
        } else {
          coBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.uuigaz.messages.BoatProtos.Shot.getDescriptor();
      }
      
      public com.github.uuigaz.messages.BoatProtos.Shot getDefaultInstanceForType() {
        return com.github.uuigaz.messages.BoatProtos.Shot.getDefaultInstance();
      }
      
      public com.github.uuigaz.messages.BoatProtos.Shot build() {
        com.github.uuigaz.messages.BoatProtos.Shot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.github.uuigaz.messages.BoatProtos.Shot buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.github.uuigaz.messages.BoatProtos.Shot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.github.uuigaz.messages.BoatProtos.Shot buildPartial() {
        com.github.uuigaz.messages.BoatProtos.Shot result = new com.github.uuigaz.messages.BoatProtos.Shot(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (coBuilder_ == null) {
          result.co_ = co_;
        } else {
          result.co_ = coBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.uuigaz.messages.BoatProtos.Shot) {
          return mergeFrom((com.github.uuigaz.messages.BoatProtos.Shot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.github.uuigaz.messages.BoatProtos.Shot other) {
        if (other == com.github.uuigaz.messages.BoatProtos.Shot.getDefaultInstance()) return this;
        if (other.hasCo()) {
          mergeCo(other.getCo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCo()) {
          
          return false;
        }
        if (!getCo().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.github.uuigaz.messages.BoatProtos.Coordinate.Builder subBuilder = com.github.uuigaz.messages.BoatProtos.Coordinate.newBuilder();
              if (hasCo()) {
                subBuilder.mergeFrom(getCo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .messages.Coordinate co = 1;
      private com.github.uuigaz.messages.BoatProtos.Coordinate co_ = com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.github.uuigaz.messages.BoatProtos.Coordinate, com.github.uuigaz.messages.BoatProtos.Coordinate.Builder, com.github.uuigaz.messages.BoatProtos.CoordinateOrBuilder> coBuilder_;
      public boolean hasCo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.github.uuigaz.messages.BoatProtos.Coordinate getCo() {
        if (coBuilder_ == null) {
          return co_;
        } else {
          return coBuilder_.getMessage();
        }
      }
      public Builder setCo(com.github.uuigaz.messages.BoatProtos.Coordinate value) {
        if (coBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          co_ = value;
          onChanged();
        } else {
          coBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setCo(
          com.github.uuigaz.messages.BoatProtos.Coordinate.Builder builderForValue) {
        if (coBuilder_ == null) {
          co_ = builderForValue.build();
          onChanged();
        } else {
          coBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeCo(com.github.uuigaz.messages.BoatProtos.Coordinate value) {
        if (coBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              co_ != com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance()) {
            co_ =
              com.github.uuigaz.messages.BoatProtos.Coordinate.newBuilder(co_).mergeFrom(value).buildPartial();
          } else {
            co_ = value;
          }
          onChanged();
        } else {
          coBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearCo() {
        if (coBuilder_ == null) {
          co_ = com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance();
          onChanged();
        } else {
          coBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.github.uuigaz.messages.BoatProtos.Coordinate.Builder getCoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getCoFieldBuilder().getBuilder();
      }
      public com.github.uuigaz.messages.BoatProtos.CoordinateOrBuilder getCoOrBuilder() {
        if (coBuilder_ != null) {
          return coBuilder_.getMessageOrBuilder();
        } else {
          return co_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.github.uuigaz.messages.BoatProtos.Coordinate, com.github.uuigaz.messages.BoatProtos.Coordinate.Builder, com.github.uuigaz.messages.BoatProtos.CoordinateOrBuilder> 
          getCoFieldBuilder() {
        if (coBuilder_ == null) {
          coBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.github.uuigaz.messages.BoatProtos.Coordinate, com.github.uuigaz.messages.BoatProtos.Coordinate.Builder, com.github.uuigaz.messages.BoatProtos.CoordinateOrBuilder>(
                  co_,
                  getParentForChildren(),
                  isClean());
          co_ = null;
        }
        return coBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:messages.Shot)
    }
    
    static {
      defaultInstance = new Shot(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messages.Shot)
  }
  
  public interface StatusReportOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bool hit = 1;
    boolean hasHit();
    boolean getHit();
  }
  public static final class StatusReport extends
      com.google.protobuf.GeneratedMessage
      implements StatusReportOrBuilder {
    // Use StatusReport.newBuilder() to construct.
    private StatusReport(Builder builder) {
      super(builder);
    }
    private StatusReport(boolean noInit) {}
    
    private static final StatusReport defaultInstance;
    public static StatusReport getDefaultInstance() {
      return defaultInstance;
    }
    
    public StatusReport getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.uuigaz.messages.BoatProtos.internal_static_messages_StatusReport_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.uuigaz.messages.BoatProtos.internal_static_messages_StatusReport_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bool hit = 1;
    public static final int HIT_FIELD_NUMBER = 1;
    private boolean hit_;
    public boolean hasHit() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getHit() {
      return hit_;
    }
    
    private void initFields() {
      hit_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasHit()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, hit_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, hit_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.github.uuigaz.messages.BoatProtos.StatusReport parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.StatusReport parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.StatusReport parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.StatusReport parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.StatusReport parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.StatusReport parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.StatusReport parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.StatusReport parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.StatusReport parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.StatusReport parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.uuigaz.messages.BoatProtos.StatusReport prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.github.uuigaz.messages.BoatProtos.StatusReportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.uuigaz.messages.BoatProtos.internal_static_messages_StatusReport_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.uuigaz.messages.BoatProtos.internal_static_messages_StatusReport_fieldAccessorTable;
      }
      
      // Construct using com.github.uuigaz.messages.BoatProtos.StatusReport.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        hit_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.uuigaz.messages.BoatProtos.StatusReport.getDescriptor();
      }
      
      public com.github.uuigaz.messages.BoatProtos.StatusReport getDefaultInstanceForType() {
        return com.github.uuigaz.messages.BoatProtos.StatusReport.getDefaultInstance();
      }
      
      public com.github.uuigaz.messages.BoatProtos.StatusReport build() {
        com.github.uuigaz.messages.BoatProtos.StatusReport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.github.uuigaz.messages.BoatProtos.StatusReport buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.github.uuigaz.messages.BoatProtos.StatusReport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.github.uuigaz.messages.BoatProtos.StatusReport buildPartial() {
        com.github.uuigaz.messages.BoatProtos.StatusReport result = new com.github.uuigaz.messages.BoatProtos.StatusReport(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hit_ = hit_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.uuigaz.messages.BoatProtos.StatusReport) {
          return mergeFrom((com.github.uuigaz.messages.BoatProtos.StatusReport)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.github.uuigaz.messages.BoatProtos.StatusReport other) {
        if (other == com.github.uuigaz.messages.BoatProtos.StatusReport.getDefaultInstance()) return this;
        if (other.hasHit()) {
          setHit(other.getHit());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasHit()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              hit_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bool hit = 1;
      private boolean hit_ ;
      public boolean hasHit() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getHit() {
        return hit_;
      }
      public Builder setHit(boolean value) {
        bitField0_ |= 0x00000001;
        hit_ = value;
        onChanged();
        return this;
      }
      public Builder clearHit() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hit_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:messages.StatusReport)
    }
    
    static {
      defaultInstance = new StatusReport(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messages.StatusReport)
  }
  
  public interface InitOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
  }
  public static final class Init extends
      com.google.protobuf.GeneratedMessage
      implements InitOrBuilder {
    // Use Init.newBuilder() to construct.
    private Init(Builder builder) {
      super(builder);
    }
    private Init(boolean noInit) {}
    
    private static final Init defaultInstance;
    public static Init getDefaultInstance() {
      return defaultInstance;
    }
    
    public Init getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.uuigaz.messages.BoatProtos.internal_static_messages_Init_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.uuigaz.messages.BoatProtos.internal_static_messages_Init_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.github.uuigaz.messages.BoatProtos.Init parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Init parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Init parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Init parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Init parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Init parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Init parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.Init parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.Init parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Init parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.uuigaz.messages.BoatProtos.Init prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.github.uuigaz.messages.BoatProtos.InitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.uuigaz.messages.BoatProtos.internal_static_messages_Init_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.uuigaz.messages.BoatProtos.internal_static_messages_Init_fieldAccessorTable;
      }
      
      // Construct using com.github.uuigaz.messages.BoatProtos.Init.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.uuigaz.messages.BoatProtos.Init.getDescriptor();
      }
      
      public com.github.uuigaz.messages.BoatProtos.Init getDefaultInstanceForType() {
        return com.github.uuigaz.messages.BoatProtos.Init.getDefaultInstance();
      }
      
      public com.github.uuigaz.messages.BoatProtos.Init build() {
        com.github.uuigaz.messages.BoatProtos.Init result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.github.uuigaz.messages.BoatProtos.Init buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.github.uuigaz.messages.BoatProtos.Init result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.github.uuigaz.messages.BoatProtos.Init buildPartial() {
        com.github.uuigaz.messages.BoatProtos.Init result = new com.github.uuigaz.messages.BoatProtos.Init(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.uuigaz.messages.BoatProtos.Init) {
          return mergeFrom((com.github.uuigaz.messages.BoatProtos.Init)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.github.uuigaz.messages.BoatProtos.Init other) {
        if (other == com.github.uuigaz.messages.BoatProtos.Init.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:messages.Init)
    }
    
    static {
      defaultInstance = new Init(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messages.Init)
  }
  
  public interface ClearToSendOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  public static final class ClearToSend extends
      com.google.protobuf.GeneratedMessage
      implements ClearToSendOrBuilder {
    // Use ClearToSend.newBuilder() to construct.
    private ClearToSend(Builder builder) {
      super(builder);
    }
    private ClearToSend(boolean noInit) {}
    
    private static final ClearToSend defaultInstance;
    public static ClearToSend getDefaultInstance() {
      return defaultInstance;
    }
    
    public ClearToSend getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.uuigaz.messages.BoatProtos.internal_static_messages_ClearToSend_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.uuigaz.messages.BoatProtos.internal_static_messages_ClearToSend_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.github.uuigaz.messages.BoatProtos.ClearToSend parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.ClearToSend parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.ClearToSend parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.ClearToSend parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.ClearToSend parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.ClearToSend parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.ClearToSend parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.ClearToSend parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.ClearToSend parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.ClearToSend parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.uuigaz.messages.BoatProtos.ClearToSend prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.github.uuigaz.messages.BoatProtos.ClearToSendOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.uuigaz.messages.BoatProtos.internal_static_messages_ClearToSend_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.uuigaz.messages.BoatProtos.internal_static_messages_ClearToSend_fieldAccessorTable;
      }
      
      // Construct using com.github.uuigaz.messages.BoatProtos.ClearToSend.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.uuigaz.messages.BoatProtos.ClearToSend.getDescriptor();
      }
      
      public com.github.uuigaz.messages.BoatProtos.ClearToSend getDefaultInstanceForType() {
        return com.github.uuigaz.messages.BoatProtos.ClearToSend.getDefaultInstance();
      }
      
      public com.github.uuigaz.messages.BoatProtos.ClearToSend build() {
        com.github.uuigaz.messages.BoatProtos.ClearToSend result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.github.uuigaz.messages.BoatProtos.ClearToSend buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.github.uuigaz.messages.BoatProtos.ClearToSend result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.github.uuigaz.messages.BoatProtos.ClearToSend buildPartial() {
        com.github.uuigaz.messages.BoatProtos.ClearToSend result = new com.github.uuigaz.messages.BoatProtos.ClearToSend(this);
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.uuigaz.messages.BoatProtos.ClearToSend) {
          return mergeFrom((com.github.uuigaz.messages.BoatProtos.ClearToSend)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.github.uuigaz.messages.BoatProtos.ClearToSend other) {
        if (other == com.github.uuigaz.messages.BoatProtos.ClearToSend.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:messages.ClearToSend)
    }
    
    static {
      defaultInstance = new ClearToSend(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messages.ClearToSend)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Coordinate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_Coordinate_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Boat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_Boat_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Shot_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_Shot_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_StatusReport_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_StatusReport_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Init_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_Init_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_ClearToSend_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_ClearToSend_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027proto/boat_protos.proto\022\010messages\"\"\n\nC" +
      "oordinate\022\t\n\001x\030\001 \002(\r\022\t\n\001y\030\002 \002(\r\"|\n\004Boat\022" +
      " \n\002co\030\001 \002(\0132\024.messages.Coordinate\"R\n\010Boa" +
      "tType\022\013\n\007CARRIER\020\005\022\016\n\nBATTLESHIP\020\004\022\013\n\007CR" +
      "UISER\020\003\022\r\n\tDESTROYER\020\002\022\r\n\tSUBMARINE\020\001\"(\n" +
      "\004Shot\022 \n\002co\030\001 \002(\0132\024.messages.Coordinate\"" +
      "\033\n\014StatusReport\022\013\n\003hit\030\001 \002(\010\"\024\n\004Init\022\014\n\004" +
      "name\030\001 \002(\t\"\r\n\013ClearToSendB\034\n\032com.github." +
      "uuigaz.messages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_messages_Coordinate_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_messages_Coordinate_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_Coordinate_descriptor,
              new java.lang.String[] { "X", "Y", },
              com.github.uuigaz.messages.BoatProtos.Coordinate.class,
              com.github.uuigaz.messages.BoatProtos.Coordinate.Builder.class);
          internal_static_messages_Boat_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_messages_Boat_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_Boat_descriptor,
              new java.lang.String[] { "Co", },
              com.github.uuigaz.messages.BoatProtos.Boat.class,
              com.github.uuigaz.messages.BoatProtos.Boat.Builder.class);
          internal_static_messages_Shot_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_messages_Shot_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_Shot_descriptor,
              new java.lang.String[] { "Co", },
              com.github.uuigaz.messages.BoatProtos.Shot.class,
              com.github.uuigaz.messages.BoatProtos.Shot.Builder.class);
          internal_static_messages_StatusReport_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_messages_StatusReport_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_StatusReport_descriptor,
              new java.lang.String[] { "Hit", },
              com.github.uuigaz.messages.BoatProtos.StatusReport.class,
              com.github.uuigaz.messages.BoatProtos.StatusReport.Builder.class);
          internal_static_messages_Init_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_messages_Init_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_Init_descriptor,
              new java.lang.String[] { "Name", },
              com.github.uuigaz.messages.BoatProtos.Init.class,
              com.github.uuigaz.messages.BoatProtos.Init.Builder.class);
          internal_static_messages_ClearToSend_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_messages_ClearToSend_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_ClearToSend_descriptor,
              new java.lang.String[] { },
              com.github.uuigaz.messages.BoatProtos.ClearToSend.class,
              com.github.uuigaz.messages.BoatProtos.ClearToSend.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
