// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/boat_protos.proto

package com.github.uuigaz.messages;

public final class BoatProtos {
  private BoatProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface CoordinateOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required uint32 x = 1;
    boolean hasX();
    int getX();
    
    // required uint32 y = 2;
    boolean hasY();
    int getY();
  }
  public static final class Coordinate extends
      com.google.protobuf.GeneratedMessageLite
      implements CoordinateOrBuilder {
    // Use Coordinate.newBuilder() to construct.
    private Coordinate(Builder builder) {
      super(builder);
    }
    private Coordinate(boolean noInit) {}
    
    private static final Coordinate defaultInstance;
    public static Coordinate getDefaultInstance() {
      return defaultInstance;
    }
    
    public Coordinate getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required uint32 x = 1;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getX() {
      return x_;
    }
    
    // required uint32 y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getY() {
      return y_;
    }
    
    private void initFields() {
      x_ = 0;
      y_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, y_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, y_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.github.uuigaz.messages.BoatProtos.Coordinate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Coordinate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Coordinate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Coordinate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Coordinate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Coordinate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Coordinate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.Coordinate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.Coordinate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Coordinate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.uuigaz.messages.BoatProtos.Coordinate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.uuigaz.messages.BoatProtos.Coordinate, Builder>
        implements com.github.uuigaz.messages.BoatProtos.CoordinateOrBuilder {
      // Construct using com.github.uuigaz.messages.BoatProtos.Coordinate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.github.uuigaz.messages.BoatProtos.Coordinate getDefaultInstanceForType() {
        return com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance();
      }
      
      public com.github.uuigaz.messages.BoatProtos.Coordinate build() {
        com.github.uuigaz.messages.BoatProtos.Coordinate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.github.uuigaz.messages.BoatProtos.Coordinate buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.github.uuigaz.messages.BoatProtos.Coordinate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.github.uuigaz.messages.BoatProtos.Coordinate buildPartial() {
        com.github.uuigaz.messages.BoatProtos.Coordinate result = new com.github.uuigaz.messages.BoatProtos.Coordinate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.github.uuigaz.messages.BoatProtos.Coordinate other) {
        if (other == com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              x_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              y_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 x = 1;
      private int x_ ;
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getX() {
        return x_;
      }
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        
        return this;
      }
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        
        return this;
      }
      
      // required uint32 y = 2;
      private int y_ ;
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getY() {
        return y_;
      }
      public Builder setY(int value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        
        return this;
      }
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:messages.Coordinate)
    }
    
    static {
      defaultInstance = new Coordinate(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messages.Coordinate)
  }
  
  public interface BoatOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .messages.Coordinate co = 1;
    boolean hasCo();
    com.github.uuigaz.messages.BoatProtos.Coordinate getCo();
  }
  public static final class Boat extends
      com.google.protobuf.GeneratedMessageLite
      implements BoatOrBuilder {
    // Use Boat.newBuilder() to construct.
    private Boat(Builder builder) {
      super(builder);
    }
    private Boat(boolean noInit) {}
    
    private static final Boat defaultInstance;
    public static Boat getDefaultInstance() {
      return defaultInstance;
    }
    
    public Boat getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public enum BoatType
        implements com.google.protobuf.Internal.EnumLite {
      CARRIER(0, 5),
      BATTLESHIP(1, 4),
      CRUISER(2, 3),
      DESTROYER(3, 2),
      SUBMARINE(4, 1),
      ;
      
      public static final int CARRIER_VALUE = 5;
      public static final int BATTLESHIP_VALUE = 4;
      public static final int CRUISER_VALUE = 3;
      public static final int DESTROYER_VALUE = 2;
      public static final int SUBMARINE_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static BoatType valueOf(int value) {
        switch (value) {
          case 5: return CARRIER;
          case 4: return BATTLESHIP;
          case 3: return CRUISER;
          case 2: return DESTROYER;
          case 1: return SUBMARINE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<BoatType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<BoatType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<BoatType>() {
              public BoatType findValueByNumber(int number) {
                return BoatType.valueOf(number);
              }
            };
      
      private final int value;
      
      private BoatType(int index, int value) {
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:messages.Boat.BoatType)
    }
    
    private int bitField0_;
    // required .messages.Coordinate co = 1;
    public static final int CO_FIELD_NUMBER = 1;
    private com.github.uuigaz.messages.BoatProtos.Coordinate co_;
    public boolean hasCo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.github.uuigaz.messages.BoatProtos.Coordinate getCo() {
      return co_;
    }
    
    private void initFields() {
      co_ = com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getCo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, co_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, co_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.github.uuigaz.messages.BoatProtos.Boat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Boat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Boat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Boat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Boat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Boat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Boat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.Boat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.Boat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Boat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.uuigaz.messages.BoatProtos.Boat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.uuigaz.messages.BoatProtos.Boat, Builder>
        implements com.github.uuigaz.messages.BoatProtos.BoatOrBuilder {
      // Construct using com.github.uuigaz.messages.BoatProtos.Boat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        co_ = com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.github.uuigaz.messages.BoatProtos.Boat getDefaultInstanceForType() {
        return com.github.uuigaz.messages.BoatProtos.Boat.getDefaultInstance();
      }
      
      public com.github.uuigaz.messages.BoatProtos.Boat build() {
        com.github.uuigaz.messages.BoatProtos.Boat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.github.uuigaz.messages.BoatProtos.Boat buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.github.uuigaz.messages.BoatProtos.Boat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.github.uuigaz.messages.BoatProtos.Boat buildPartial() {
        com.github.uuigaz.messages.BoatProtos.Boat result = new com.github.uuigaz.messages.BoatProtos.Boat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.co_ = co_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.github.uuigaz.messages.BoatProtos.Boat other) {
        if (other == com.github.uuigaz.messages.BoatProtos.Boat.getDefaultInstance()) return this;
        if (other.hasCo()) {
          mergeCo(other.getCo());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCo()) {
          
          return false;
        }
        if (!getCo().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              com.github.uuigaz.messages.BoatProtos.Coordinate.Builder subBuilder = com.github.uuigaz.messages.BoatProtos.Coordinate.newBuilder();
              if (hasCo()) {
                subBuilder.mergeFrom(getCo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .messages.Coordinate co = 1;
      private com.github.uuigaz.messages.BoatProtos.Coordinate co_ = com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance();
      public boolean hasCo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.github.uuigaz.messages.BoatProtos.Coordinate getCo() {
        return co_;
      }
      public Builder setCo(com.github.uuigaz.messages.BoatProtos.Coordinate value) {
        if (value == null) {
          throw new NullPointerException();
        }
        co_ = value;
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setCo(
          com.github.uuigaz.messages.BoatProtos.Coordinate.Builder builderForValue) {
        co_ = builderForValue.build();
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeCo(com.github.uuigaz.messages.BoatProtos.Coordinate value) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            co_ != com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance()) {
          co_ =
            com.github.uuigaz.messages.BoatProtos.Coordinate.newBuilder(co_).mergeFrom(value).buildPartial();
        } else {
          co_ = value;
        }
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearCo() {
        co_ = com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:messages.Boat)
    }
    
    static {
      defaultInstance = new Boat(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messages.Boat)
  }
  
  public interface ShotOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .messages.Coordinate co = 1;
    boolean hasCo();
    com.github.uuigaz.messages.BoatProtos.Coordinate getCo();
  }
  public static final class Shot extends
      com.google.protobuf.GeneratedMessageLite
      implements ShotOrBuilder {
    // Use Shot.newBuilder() to construct.
    private Shot(Builder builder) {
      super(builder);
    }
    private Shot(boolean noInit) {}
    
    private static final Shot defaultInstance;
    public static Shot getDefaultInstance() {
      return defaultInstance;
    }
    
    public Shot getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required .messages.Coordinate co = 1;
    public static final int CO_FIELD_NUMBER = 1;
    private com.github.uuigaz.messages.BoatProtos.Coordinate co_;
    public boolean hasCo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.github.uuigaz.messages.BoatProtos.Coordinate getCo() {
      return co_;
    }
    
    private void initFields() {
      co_ = com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getCo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, co_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, co_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.github.uuigaz.messages.BoatProtos.Shot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Shot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Shot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Shot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Shot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Shot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Shot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.Shot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.Shot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Shot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.uuigaz.messages.BoatProtos.Shot prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.uuigaz.messages.BoatProtos.Shot, Builder>
        implements com.github.uuigaz.messages.BoatProtos.ShotOrBuilder {
      // Construct using com.github.uuigaz.messages.BoatProtos.Shot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        co_ = com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.github.uuigaz.messages.BoatProtos.Shot getDefaultInstanceForType() {
        return com.github.uuigaz.messages.BoatProtos.Shot.getDefaultInstance();
      }
      
      public com.github.uuigaz.messages.BoatProtos.Shot build() {
        com.github.uuigaz.messages.BoatProtos.Shot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.github.uuigaz.messages.BoatProtos.Shot buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.github.uuigaz.messages.BoatProtos.Shot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.github.uuigaz.messages.BoatProtos.Shot buildPartial() {
        com.github.uuigaz.messages.BoatProtos.Shot result = new com.github.uuigaz.messages.BoatProtos.Shot(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.co_ = co_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.github.uuigaz.messages.BoatProtos.Shot other) {
        if (other == com.github.uuigaz.messages.BoatProtos.Shot.getDefaultInstance()) return this;
        if (other.hasCo()) {
          mergeCo(other.getCo());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCo()) {
          
          return false;
        }
        if (!getCo().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              com.github.uuigaz.messages.BoatProtos.Coordinate.Builder subBuilder = com.github.uuigaz.messages.BoatProtos.Coordinate.newBuilder();
              if (hasCo()) {
                subBuilder.mergeFrom(getCo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .messages.Coordinate co = 1;
      private com.github.uuigaz.messages.BoatProtos.Coordinate co_ = com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance();
      public boolean hasCo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.github.uuigaz.messages.BoatProtos.Coordinate getCo() {
        return co_;
      }
      public Builder setCo(com.github.uuigaz.messages.BoatProtos.Coordinate value) {
        if (value == null) {
          throw new NullPointerException();
        }
        co_ = value;
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setCo(
          com.github.uuigaz.messages.BoatProtos.Coordinate.Builder builderForValue) {
        co_ = builderForValue.build();
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeCo(com.github.uuigaz.messages.BoatProtos.Coordinate value) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            co_ != com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance()) {
          co_ =
            com.github.uuigaz.messages.BoatProtos.Coordinate.newBuilder(co_).mergeFrom(value).buildPartial();
        } else {
          co_ = value;
        }
        
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearCo() {
        co_ = com.github.uuigaz.messages.BoatProtos.Coordinate.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:messages.Shot)
    }
    
    static {
      defaultInstance = new Shot(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messages.Shot)
  }
  
  public interface BoardOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // repeated .messages.Boat boats = 1;
    java.util.List<com.github.uuigaz.messages.BoatProtos.Boat> 
        getBoatsList();
    com.github.uuigaz.messages.BoatProtos.Boat getBoats(int index);
    int getBoatsCount();
  }
  public static final class Board extends
      com.google.protobuf.GeneratedMessageLite
      implements BoardOrBuilder {
    // Use Board.newBuilder() to construct.
    private Board(Builder builder) {
      super(builder);
    }
    private Board(boolean noInit) {}
    
    private static final Board defaultInstance;
    public static Board getDefaultInstance() {
      return defaultInstance;
    }
    
    public Board getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // repeated .messages.Boat boats = 1;
    public static final int BOATS_FIELD_NUMBER = 1;
    private java.util.List<com.github.uuigaz.messages.BoatProtos.Boat> boats_;
    public java.util.List<com.github.uuigaz.messages.BoatProtos.Boat> getBoatsList() {
      return boats_;
    }
    public java.util.List<? extends com.github.uuigaz.messages.BoatProtos.BoatOrBuilder> 
        getBoatsOrBuilderList() {
      return boats_;
    }
    public int getBoatsCount() {
      return boats_.size();
    }
    public com.github.uuigaz.messages.BoatProtos.Boat getBoats(int index) {
      return boats_.get(index);
    }
    public com.github.uuigaz.messages.BoatProtos.BoatOrBuilder getBoatsOrBuilder(
        int index) {
      return boats_.get(index);
    }
    
    private void initFields() {
      boats_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getBoatsCount(); i++) {
        if (!getBoats(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < boats_.size(); i++) {
        output.writeMessage(1, boats_.get(i));
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < boats_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, boats_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.github.uuigaz.messages.BoatProtos.Board parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Board parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Board parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Board parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Board parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Board parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Board parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.Board parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.Board parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Board parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.uuigaz.messages.BoatProtos.Board prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.uuigaz.messages.BoatProtos.Board, Builder>
        implements com.github.uuigaz.messages.BoatProtos.BoardOrBuilder {
      // Construct using com.github.uuigaz.messages.BoatProtos.Board.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        boats_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.github.uuigaz.messages.BoatProtos.Board getDefaultInstanceForType() {
        return com.github.uuigaz.messages.BoatProtos.Board.getDefaultInstance();
      }
      
      public com.github.uuigaz.messages.BoatProtos.Board build() {
        com.github.uuigaz.messages.BoatProtos.Board result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.github.uuigaz.messages.BoatProtos.Board buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.github.uuigaz.messages.BoatProtos.Board result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.github.uuigaz.messages.BoatProtos.Board buildPartial() {
        com.github.uuigaz.messages.BoatProtos.Board result = new com.github.uuigaz.messages.BoatProtos.Board(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          boats_ = java.util.Collections.unmodifiableList(boats_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.boats_ = boats_;
        return result;
      }
      
      public Builder mergeFrom(com.github.uuigaz.messages.BoatProtos.Board other) {
        if (other == com.github.uuigaz.messages.BoatProtos.Board.getDefaultInstance()) return this;
        if (!other.boats_.isEmpty()) {
          if (boats_.isEmpty()) {
            boats_ = other.boats_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBoatsIsMutable();
            boats_.addAll(other.boats_);
          }
          
        }
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getBoatsCount(); i++) {
          if (!getBoats(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              com.github.uuigaz.messages.BoatProtos.Boat.Builder subBuilder = com.github.uuigaz.messages.BoatProtos.Boat.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addBoats(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .messages.Boat boats = 1;
      private java.util.List<com.github.uuigaz.messages.BoatProtos.Boat> boats_ =
        java.util.Collections.emptyList();
      private void ensureBoatsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          boats_ = new java.util.ArrayList<com.github.uuigaz.messages.BoatProtos.Boat>(boats_);
          bitField0_ |= 0x00000001;
         }
      }
      
      public java.util.List<com.github.uuigaz.messages.BoatProtos.Boat> getBoatsList() {
        return java.util.Collections.unmodifiableList(boats_);
      }
      public int getBoatsCount() {
        return boats_.size();
      }
      public com.github.uuigaz.messages.BoatProtos.Boat getBoats(int index) {
        return boats_.get(index);
      }
      public Builder setBoats(
          int index, com.github.uuigaz.messages.BoatProtos.Boat value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBoatsIsMutable();
        boats_.set(index, value);
        
        return this;
      }
      public Builder setBoats(
          int index, com.github.uuigaz.messages.BoatProtos.Boat.Builder builderForValue) {
        ensureBoatsIsMutable();
        boats_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addBoats(com.github.uuigaz.messages.BoatProtos.Boat value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBoatsIsMutable();
        boats_.add(value);
        
        return this;
      }
      public Builder addBoats(
          int index, com.github.uuigaz.messages.BoatProtos.Boat value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBoatsIsMutable();
        boats_.add(index, value);
        
        return this;
      }
      public Builder addBoats(
          com.github.uuigaz.messages.BoatProtos.Boat.Builder builderForValue) {
        ensureBoatsIsMutable();
        boats_.add(builderForValue.build());
        
        return this;
      }
      public Builder addBoats(
          int index, com.github.uuigaz.messages.BoatProtos.Boat.Builder builderForValue) {
        ensureBoatsIsMutable();
        boats_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllBoats(
          java.lang.Iterable<? extends com.github.uuigaz.messages.BoatProtos.Boat> values) {
        ensureBoatsIsMutable();
        super.addAll(values, boats_);
        
        return this;
      }
      public Builder clearBoats() {
        boats_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }
      public Builder removeBoats(int index) {
        ensureBoatsIsMutable();
        boats_.remove(index);
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:messages.Board)
    }
    
    static {
      defaultInstance = new Board(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messages.Board)
  }
  
  public interface StatusReportOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required bool hit = 1;
    boolean hasHit();
    boolean getHit();
  }
  public static final class StatusReport extends
      com.google.protobuf.GeneratedMessageLite
      implements StatusReportOrBuilder {
    // Use StatusReport.newBuilder() to construct.
    private StatusReport(Builder builder) {
      super(builder);
    }
    private StatusReport(boolean noInit) {}
    
    private static final StatusReport defaultInstance;
    public static StatusReport getDefaultInstance() {
      return defaultInstance;
    }
    
    public StatusReport getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required bool hit = 1;
    public static final int HIT_FIELD_NUMBER = 1;
    private boolean hit_;
    public boolean hasHit() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getHit() {
      return hit_;
    }
    
    private void initFields() {
      hit_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasHit()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, hit_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, hit_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.github.uuigaz.messages.BoatProtos.StatusReport parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.StatusReport parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.StatusReport parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.StatusReport parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.StatusReport parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.StatusReport parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.StatusReport parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.StatusReport parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.StatusReport parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.StatusReport parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.uuigaz.messages.BoatProtos.StatusReport prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.uuigaz.messages.BoatProtos.StatusReport, Builder>
        implements com.github.uuigaz.messages.BoatProtos.StatusReportOrBuilder {
      // Construct using com.github.uuigaz.messages.BoatProtos.StatusReport.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        hit_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.github.uuigaz.messages.BoatProtos.StatusReport getDefaultInstanceForType() {
        return com.github.uuigaz.messages.BoatProtos.StatusReport.getDefaultInstance();
      }
      
      public com.github.uuigaz.messages.BoatProtos.StatusReport build() {
        com.github.uuigaz.messages.BoatProtos.StatusReport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.github.uuigaz.messages.BoatProtos.StatusReport buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.github.uuigaz.messages.BoatProtos.StatusReport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.github.uuigaz.messages.BoatProtos.StatusReport buildPartial() {
        com.github.uuigaz.messages.BoatProtos.StatusReport result = new com.github.uuigaz.messages.BoatProtos.StatusReport(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hit_ = hit_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.github.uuigaz.messages.BoatProtos.StatusReport other) {
        if (other == com.github.uuigaz.messages.BoatProtos.StatusReport.getDefaultInstance()) return this;
        if (other.hasHit()) {
          setHit(other.getHit());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasHit()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              hit_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bool hit = 1;
      private boolean hit_ ;
      public boolean hasHit() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getHit() {
        return hit_;
      }
      public Builder setHit(boolean value) {
        bitField0_ |= 0x00000001;
        hit_ = value;
        
        return this;
      }
      public Builder clearHit() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hit_ = false;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:messages.StatusReport)
    }
    
    static {
      defaultInstance = new StatusReport(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messages.StatusReport)
  }
  
  public interface IdentOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
  }
  public static final class Ident extends
      com.google.protobuf.GeneratedMessageLite
      implements IdentOrBuilder {
    // Use Ident.newBuilder() to construct.
    private Ident(Builder builder) {
      super(builder);
    }
    private Ident(boolean noInit) {}
    
    private static final Ident defaultInstance;
    public static Ident getDefaultInstance() {
      return defaultInstance;
    }
    
    public Ident getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.github.uuigaz.messages.BoatProtos.Ident parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Ident parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Ident parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Ident parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Ident parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Ident parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Ident parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.Ident parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.Ident parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.Ident parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.uuigaz.messages.BoatProtos.Ident prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.uuigaz.messages.BoatProtos.Ident, Builder>
        implements com.github.uuigaz.messages.BoatProtos.IdentOrBuilder {
      // Construct using com.github.uuigaz.messages.BoatProtos.Ident.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.github.uuigaz.messages.BoatProtos.Ident getDefaultInstanceForType() {
        return com.github.uuigaz.messages.BoatProtos.Ident.getDefaultInstance();
      }
      
      public com.github.uuigaz.messages.BoatProtos.Ident build() {
        com.github.uuigaz.messages.BoatProtos.Ident result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.github.uuigaz.messages.BoatProtos.Ident buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.github.uuigaz.messages.BoatProtos.Ident result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.github.uuigaz.messages.BoatProtos.Ident buildPartial() {
        com.github.uuigaz.messages.BoatProtos.Ident result = new com.github.uuigaz.messages.BoatProtos.Ident(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(com.github.uuigaz.messages.BoatProtos.Ident other) {
        if (other == com.github.uuigaz.messages.BoatProtos.Ident.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        
      }
      
      // @@protoc_insertion_point(builder_scope:messages.Ident)
    }
    
    static {
      defaultInstance = new Ident(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messages.Ident)
  }
  
  public interface CTSOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
  }
  public static final class CTS extends
      com.google.protobuf.GeneratedMessageLite
      implements CTSOrBuilder {
    // Use CTS.newBuilder() to construct.
    private CTS(Builder builder) {
      super(builder);
    }
    private CTS(boolean noInit) {}
    
    private static final CTS defaultInstance;
    public static CTS getDefaultInstance() {
      return defaultInstance;
    }
    
    public CTS getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.github.uuigaz.messages.BoatProtos.CTS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.CTS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.CTS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.CTS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.CTS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.CTS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.CTS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.CTS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.github.uuigaz.messages.BoatProtos.CTS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.github.uuigaz.messages.BoatProtos.CTS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.uuigaz.messages.BoatProtos.CTS prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.uuigaz.messages.BoatProtos.CTS, Builder>
        implements com.github.uuigaz.messages.BoatProtos.CTSOrBuilder {
      // Construct using com.github.uuigaz.messages.BoatProtos.CTS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.github.uuigaz.messages.BoatProtos.CTS getDefaultInstanceForType() {
        return com.github.uuigaz.messages.BoatProtos.CTS.getDefaultInstance();
      }
      
      public com.github.uuigaz.messages.BoatProtos.CTS build() {
        com.github.uuigaz.messages.BoatProtos.CTS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.github.uuigaz.messages.BoatProtos.CTS buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.github.uuigaz.messages.BoatProtos.CTS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.github.uuigaz.messages.BoatProtos.CTS buildPartial() {
        com.github.uuigaz.messages.BoatProtos.CTS result = new com.github.uuigaz.messages.BoatProtos.CTS(this);
        return result;
      }
      
      public Builder mergeFrom(com.github.uuigaz.messages.BoatProtos.CTS other) {
        if (other == com.github.uuigaz.messages.BoatProtos.CTS.getDefaultInstance()) return this;
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:messages.CTS)
    }
    
    static {
      defaultInstance = new CTS(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messages.CTS)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
