# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='proto/boat_protos.proto',
  package='messages',
  serialized_pb='\n\x17proto/boat_protos.proto\x12\x08messages\"v\n\x0b\x42\x61seMessage\x12\x10\n\x08yourTurn\x18\x01 \x01(\x08\x12\x0f\n\x07\x65ndGame\x18\x02 \x01(\x08\x12\x1c\n\x04\x66ire\x18\x03 \x01(\x0b\x32\x0e.messages.Fire\x12&\n\x06report\x18\x04 \x01(\x0b\x32\x16.messages.StatusReport\"7\n\x04Init\x12\x0f\n\x07newGame\x18\x01 \x01(\x08\x12\x1e\n\x05\x62oard\x18\x02 \x01(\x0b\x32\x0f.messages.Board\"\xc1\x02\n\x05\x42oard\x12#\n\x05\x62oats\x18\x06 \x03(\x0b\x32\x14.messages.Board.Boat\x1a\x92\x02\n\x04\x42oat\x12\t\n\x01x\x18\x01 \x02(\r\x12\t\n\x01y\x18\x02 \x02(\r\x12+\n\x04type\x18\x03 \x02(\x0e\x32\x1d.messages.Board.Boat.BoatType\x12\x31\n\tdirection\x18\x04 \x02(\x0e\x32\x1e.messages.Board.Boat.Direction\x12\x0c\n\x04hits\x18\x05 \x01(\r\"2\n\tDirection\x12\x08\n\x04\x44OWN\x10\x01\x12\t\n\x05RIGHT\x10\x02\x12\x06\n\x02UP\x10\x03\x12\x08\n\x04LEFT\x10\x04\"R\n\x08\x42oatType\x12\x0b\n\x07\x43\x41RRIER\x10\x05\x12\x0e\n\nBATTLESHIP\x10\x04\x12\x0b\n\x07\x43RUISER\x10\x03\x12\r\n\tDESTROYER\x10\x02\x12\r\n\tSUBMARINE\x10\x01\"\x1c\n\x04\x46ire\x12\t\n\x01x\x18\x01 \x02(\r\x12\t\n\x01y\x18\x02 \x02(\r\"\x1b\n\x0cStatusReport\x12\x0b\n\x03hit\x18\x01 \x01(\x08\"\x15\n\x05Ident\x12\x0c\n\x04name\x18\x01 \x02(\tB\x1e\n\x1a\x63om.github.uuigaz.messagesH\x03')



_BOARD_BOAT_DIRECTION = descriptor.EnumDescriptor(
  name='Direction',
  full_name='messages.Board.Boat.Direction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='DOWN', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RIGHT', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='UP', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LEFT', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=402,
  serialized_end=452,
)

_BOARD_BOAT_BOATTYPE = descriptor.EnumDescriptor(
  name='BoatType',
  full_name='messages.Board.Boat.BoatType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='CARRIER', index=0, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BATTLESHIP', index=1, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CRUISER', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DESTROYER', index=3, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SUBMARINE', index=4, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=454,
  serialized_end=536,
)


_BASEMESSAGE = descriptor.Descriptor(
  name='BaseMessage',
  full_name='messages.BaseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='yourTurn', full_name='messages.BaseMessage.yourTurn', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='endGame', full_name='messages.BaseMessage.endGame', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fire', full_name='messages.BaseMessage.fire', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='report', full_name='messages.BaseMessage.report', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=37,
  serialized_end=155,
)


_INIT = descriptor.Descriptor(
  name='Init',
  full_name='messages.Init',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='newGame', full_name='messages.Init.newGame', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='board', full_name='messages.Init.board', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=157,
  serialized_end=212,
)


_BOARD_BOAT = descriptor.Descriptor(
  name='Boat',
  full_name='messages.Board.Boat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='x', full_name='messages.Board.Boat.x', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y', full_name='messages.Board.Boat.y', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='messages.Board.Boat.type', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='direction', full_name='messages.Board.Boat.direction', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hits', full_name='messages.Board.Boat.hits', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BOARD_BOAT_DIRECTION,
    _BOARD_BOAT_BOATTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=262,
  serialized_end=536,
)

_BOARD = descriptor.Descriptor(
  name='Board',
  full_name='messages.Board',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='boats', full_name='messages.Board.boats', index=0,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_BOARD_BOAT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=215,
  serialized_end=536,
)


_FIRE = descriptor.Descriptor(
  name='Fire',
  full_name='messages.Fire',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='x', full_name='messages.Fire.x', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y', full_name='messages.Fire.y', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=538,
  serialized_end=566,
)


_STATUSREPORT = descriptor.Descriptor(
  name='StatusReport',
  full_name='messages.StatusReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hit', full_name='messages.StatusReport.hit', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=568,
  serialized_end=595,
)


_IDENT = descriptor.Descriptor(
  name='Ident',
  full_name='messages.Ident',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='messages.Ident.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=597,
  serialized_end=618,
)

_BASEMESSAGE.fields_by_name['fire'].message_type = _FIRE
_BASEMESSAGE.fields_by_name['report'].message_type = _STATUSREPORT
_INIT.fields_by_name['board'].message_type = _BOARD
_BOARD_BOAT.fields_by_name['type'].enum_type = _BOARD_BOAT_BOATTYPE
_BOARD_BOAT.fields_by_name['direction'].enum_type = _BOARD_BOAT_DIRECTION
_BOARD_BOAT.containing_type = _BOARD;
_BOARD_BOAT_DIRECTION.containing_type = _BOARD_BOAT;
_BOARD_BOAT_BOATTYPE.containing_type = _BOARD_BOAT;
_BOARD.fields_by_name['boats'].message_type = _BOARD_BOAT
DESCRIPTOR.message_types_by_name['BaseMessage'] = _BASEMESSAGE
DESCRIPTOR.message_types_by_name['Init'] = _INIT
DESCRIPTOR.message_types_by_name['Board'] = _BOARD
DESCRIPTOR.message_types_by_name['Fire'] = _FIRE
DESCRIPTOR.message_types_by_name['StatusReport'] = _STATUSREPORT
DESCRIPTOR.message_types_by_name['Ident'] = _IDENT

class BaseMessage(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _BASEMESSAGE

    # @@protoc_insertion_point(class_scope:messages.BaseMessage)

class Init(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _INIT

    # @@protoc_insertion_point(class_scope:messages.Init)

class Board(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType

    class Boat(message.Message):
        __metaclass__ = reflection.GeneratedProtocolMessageType
        DESCRIPTOR = _BOARD_BOAT

        # @@protoc_insertion_point(class_scope:messages.Board.Boat)
    DESCRIPTOR = _BOARD

    # @@protoc_insertion_point(class_scope:messages.Board)

class Fire(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _FIRE

    # @@protoc_insertion_point(class_scope:messages.Fire)

class StatusReport(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _STATUSREPORT

    # @@protoc_insertion_point(class_scope:messages.StatusReport)

class Ident(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _IDENT

    # @@protoc_insertion_point(class_scope:messages.Ident)

# @@protoc_insertion_point(module_scope)
